# # Basic workflox to build and deploy the app in FTP

# name: Next.js CI + FTP

# on:
#   push:
#     branches: [ main ]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: [10.x, 12.x, 14.x, 15.x]
#         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
#     steps:
#     - uses: actions/checkout@v2
#     - name: Next.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v1
#       with:
#         node-version: ${{ matrix.node-version }}
#     - run: npm ci
#     # TODO: add tests
#     - run: npm run build --if-present && npm run export
#     - run: ftp -n ${FTP_HOST} <<EOF
#     - run: user ${FTP_USER} ${FTP_PASSWORD}
#     - run: cd www/${FTP_PROJECT_DIR}
#     - run: put .
#     - run: bye >>EOF
